# -*- coding: utf-8 -*-
"""Wikipedia Entity Finder (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBx9YbKviSAPjDLDhuKMJhil0969qBku
"""

!pip install wikipedia

import wikipedia

wikipedia.set_lang("en")

wikipedia.search("probate")

wikipedia.page("'Probate'").content

!python -m spacy download en

!pip install spacy

import spacy

NER = spacy.load("en_core_web_sm")

text= NER(wikipedia.page("'Probate'").content)

for w in text.ents:
    print(w.text,w.label_)

spacy.displacy.render(text, style="ent",jupyter=True)

